version: '3.2'
services:
  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    environment:
      - WEBHOOK_TOKEN=local_token
      - FB_ACCESS_TOKEN=token
    command:
      - ./run.sh